Feature/feature 1
Takhir30/Calc pull request #1
Opened 2018-01-15 08:57 UTC by Takhir30

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
>      expr_list[expr_list.index('+')-1:expr_list.index('+')+1+1] = [str(float(expr_list[expr_list.index('+')-1]) + float(expr_list[expr_list.index('+')+1]))]
можно записать exp_list.index('+') одтн раз в переменную, и там уже с ней работать 
+1+1  можно записать как 2

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
также список, и использовать как в синусе

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
тут тоже будет полезен список только проверять на то что i нет в этом списке

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
>          elif i == '-' :
можно создать список из операций 
и проверять на наличее в списке

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
>              else:
тут можно ипользовать elif

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
> +    if "cos" in num:
использовать elif

2018-01-15 12:07 UTC, Syphi commented on calc_1.py
> +        return(calc(sinus(num)))
использовать return без скобок

2018-01-15 12:25 UTC, strelass requested changes
Операции * / имеют одинаковый высокий приоритет, если поменять их местами результат не станет правильным. Для того, чтобы корректно посчитать значение такого выражения его нужно привести к [польской записи](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F) либо подумать как применить [диаграммы Вирта](https://studopedia.ru/5_83096_diagrammi-virta.html).

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +import argparse,math
импорты модулей должны быть в отдельных строках

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +        return(calc(sinus(num)))
лишние скобки

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +
расстояние между функциями 2 строки

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +    expr_list = expr_list.split(',')
зачем формировать строку, а потом делать из неё список, когда можно сразу делать список?

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +    new_expr_str = expr_str.replace('sin' + b[3:],str(round(math.sin(int(b[3:])*math.pi/180),2)))
по стандартам между знаками арифметических операций должны быть пробелы, после запятой должен быть пробел

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +        else: break
break перенести в новую строку, места предостаточно ;)

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +    expr_list[expr_list.index('+')-1:expr_list.index('+')+1+1] = [str(float(expr_list[expr_list.index('+')-1]) + float(expr_list[expr_list.index('+')+1]))]
превышена рекомендуемая длина строки (250 символов)
не стоит писать всё и сразу, понижается читаемость. напиши несколько промежуточных шагов перед этим

2018-01-15 12:25 UTC, strelass commented on calc_1.py
> +def calc(num):
лучше назвать не num а expression или exp, так имеет больше смысла

2018-01-15 12:28 UTC, strelass commented on calc_1.py
> +    if "cos" in num:
тут return в каждом кейсе, использовать elif не имеет смысла

2018-01-15 12:30 UTC, strelass commented on calc_1.py
>          elif i == '-' :
лучше не список а словарь, например
```
operations = {
 '-': sub,
 '+': add
}
```

2018-01-15 12:32 UTC, strelass commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
например
```
if i in '-+/*':
   do_smth()
```

2018-01-15 12:43 UTC, Takhir30 commented on calc_1.py
> +    expr_list = expr_list.split(',')
a = '12+1'
b  = list(a)  (b = ['1' , '2' , '+' , '1'] , а надо ['12' , '+', '1'])

2018-01-15 12:59 UTC, Takhir30 commented on calc_1.py
>              else:
Если имеется ввиду elif для перечисления матоператоров, я специально использовал вложенное условие с return, чтобы соблюсти порядок вычислений

2018-01-15 13:03 UTC, Takhir30 commented on calc_1.py
> +        return(calc(sinus(num)))
Все return или только когда возвращают функцию ?

2018-01-15 13:09 UTC, Takhir30 commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
почему при условии isdigit or '.' , python пропускает и +-*/  ?

2018-01-15 14:02 UTC, strelass commented on calc_1.py
> +    expr_list = expr_list.split(',')
```
temp = ''
for i in expr:
   if i.isalpha():
      temp += i
   elif i in '-+*/':
      if len(temp) > 0:
         expr_list += [temp]
         temp = ''
      expr_list += [i]
if len(temp) > 0:
   expr_list += [temp]
```

2018-01-15 14:04 UTC, strelass commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
можно пример кода посмотреть?

2018-01-15 14:05 UTC, strelass commented on calc_1.py
> +        return(calc(sinus(num)))
неважно, скобки лишние, даже при возвращении списка их не нужно использовать
```
return 2
return sin(2)
return 2, 3
return await calc(2)
```

2018-01-15 14:29 UTC, Takhir30 commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
def sinus(expr_str):
    b = ''
    for i in expr_str[expr_str.find('sin'):]:
        if i.isdigit or i == '.' :
            b += i
        else:
            break
    return b
print(sinus('2*sin30+32+100'))

2018-01-15 14:33 UTC, strelass commented on calc_1.py
> +        if i != '-' and i != '+' and i != '/' and i != '*':
isdigit это функция, ты её не вызываешь, питон сравнивает её с None и возвращает тебе True всегда
`if i.isdigit() or i == '.': pass`

p.s. github поддерживает [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

2018-01-16 14:08 UTC, strelass requested changes

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    math_action = {'sin':sinus, "cos":cosinus, '/':div,
Дикт лучше записывать каждую пару в новой строке. Пробел после двоеточия

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +        for i in ['sin','cos','/','*','-','+']:
пробелы после запятых

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +                if expr == "ZeroDivisionError" :
вместо текстовой ошибки сделать обработчик ошибок

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +        return ("%.2f" % float(expr[0]))
лишние скобки

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    expr_list = expr_list.split(',')
сделать генерацию списка сразу, а не конвертить его из строки

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +            if i.isdigit or i == '.' or i.isalpa:
```
type(i.isdigit)
type(i.isdigit())
```
посмотри что получится

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    new_expr_str = expr_str.replace('sin' + b[3:], str(round(math.sin(int(b[3:]) * math.pi/180), 2)))
нам не нужен `round`

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    expr_list[plus - 1:plus + 2] = [str(float(expr_list[plus - 1]) + float(expr_list[plus + 1]))]
вычисления `plus - 1` и `plus + 2` повторяются, нужно создать промежуточные переменные

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    return (calc(expr_list))
лишние скобки

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    new_expr_str = expr_str.replace('cos' + b[3:], str(round(math.sin(int(b[3:]) * math.pi / 180), 2)))
зачем каждый раз перегонять из строки в число и обратно?

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +    with open(input(),'a+') as new_line:
пробел после запятой
было бы неплохо написать что-то пользователю, чтобы он понял что от него хотят

2018-01-16 14:08 UTC, strelass commented on calc_1.py
> +def Main():
названия финкций должны быть snake case

2018-01-17 12:19 UTC, strelass requested changes
Обрати внимание на пробелы

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +                return math_action[i](i,expr)
пробел после запятой

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +    try:
try-except должен ограничивать только тот блок, в котором ожидается ошибка. у тебя ошибка может возникнуть только про делении, следовательно и try-except нужно поместить туда

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +def a_num(sign, expr):
из названия метода не понятно что он делает

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +        if i.isdigit() or i == '.':
если цикл останавливается по одному ифу может лучше использовать while?

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +        new_expr = expr.replace(trig, str(math.sin(rad_to_degree)))
опять перевод в строку

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +    new_expr = expr.replace(expr[a_index:b_index],str(a+b))
пробел после запятой, пробел перед и после арифметической операции

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +def mult(sign,expr):
методы add, sub, div, mult абсолютно одинаковые, за исключением одной операции, подумай как заменить их одним

2018-01-17 12:19 UTC, strelass commented on calc_1.py
> +def add(sign,expr):
пробел после запятой

2018-01-17 15:41 UTC, Takhir30 commented on calc_1.py
> +    try:
done

2018-01-17 15:41 UTC, Takhir30 commented on calc_1.py
> +                return math_action[i](i,expr)
done

2018-01-17 15:41 UTC, Takhir30 commented on calc_1.py
> +def a_num(sign, expr):
done

2018-01-17 15:44 UTC, Takhir30 commented on calc_1.py
> +        if i.isdigit() or i == '.':
с for, как по мне,  проще не выйти за пределы списка. С while долго мучился пытаясь подобрать нужные индексы для невыхода за границы списка

2018-01-17 15:46 UTC, Takhir30 commented on calc_1.py
> +        new_expr = expr.replace(trig, str(math.sin(rad_to_degree)))
А как по другому?  replace - строковый метод, функция синуса возвращает float

2018-01-17 15:46 UTC, Takhir30 commented on calc_1.py
> +def add(sign,expr):
done

2018-01-17 15:46 UTC, Takhir30 commented on calc_1.py
> +    new_expr = expr.replace(expr[a_index:b_index],str(a+b))
done

2018-01-17 15:46 UTC, Takhir30 commented on calc_1.py
> +def mult(sign,expr):
done

2018-01-18 09:05 UTC, strelass requested changes

2018-01-18 09:05 UTC, strelass commented on calc_1.py
> +    return a + b
эти функции уже существуют
```
float.__add__
float.__sub__
float.__mul__
float.__truediv__
```

2018-01-18 09:05 UTC, strelass commented on calc_1.py
> +        new_expr = expr.replace(trig, str(math.sin(rad_to_degree)))
по-прежнему результат кастится в строку

2018-01-18 14:10 UTC, strelass approved these changes

2018-01-18 14:11 UTC, merged