1) Added parenthesis
Takhir30/Calc pull request #4
Opened 2018-01-21 14:19 UTC by Takhir30

2) Unary minus
3) Correct input

2018-01-21 15:17 UTC, strelass requested changes

2018-01-21 15:17 UTC, strelass commented on calc_1.py
> +    expr = expr.replace(' ','')    #удаляем пробелы
комментарии только на английском
пробел после запятой

2018-01-21 15:17 UTC, strelass commented on calc_1.py
> +            expr = expr.replace(i,'')
пробел после запятой

2018-01-21 15:17 UTC, strelass commented on calc_1.py
> +        if i not in '123456789.()+-*/':
допустимые символы лучше вынести в глобальную переменную и поместить её вначале файла

2018-01-21 15:17 UTC, strelass commented on calc_1.py
> +            return 'Wrong input!!! You may use only "123456789.()+-*/" symbols! Try again!'
а здесь использовать эту переменную для отображения ошибки

2018-01-21 15:17 UTC, strelass commented on calc_1.py
> +        for symbol in ['(', '+-', '--', '*-', '/-', '+', '-', '*', '/']:
+-, --, *-, /- так никто не пишет, унарный минус может быть только вначале выражения (или после открытия скобки)

2018-01-22 06:46 UTC, Takhir30 commented on calc_1.py
> +        for symbol in ['(', '+-', '--', '*-', '/-', '+', '-', '*', '/']:
Как от них '+-', '--'
, '*-', '/-' избавится? Подкинь идею

2018-01-22 16:06 UTC, strelass requested changes

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +    expr = expr.replace(' ', '')    #Removing some extra space's
тут лучше использовать regexp, можешь поиграться [тут](http://regex101.com/) заодно посмотришь либу `re`

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +
лишняя пустая строка

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +    expr_list = expr_list.replace(',,',',').split(',')
а когда могут быть две запятые?

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +    expr_list = [x for x in expr_list if x]
используй тут билтин `filter`

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +        return  float('%.2f' % float(expr[0]))
лишний пробел

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +            right_index = i_index
почему тут `.index()` не используешь?

2018-01-22 16:06 UTC, strelass commented on calc_1.py
> +    expr[left_index:right_index + 1] = [calc(expr[left_index + 1:right_index])]
это уже похоже на правду

2018-01-22 16:06 UTC, strelass commented on calc_1.py
>  def trigonometry(expr):
почему решил переделать?

2018-01-22 16:16 UTC, Takhir30 commented on calc_1.py
> +
done

2018-01-22 16:18 UTC, Takhir30 commented on calc_1.py
> +    expr_list = expr_list.replace(',,',',').split(',')
Когда выражение начинается с '(-...  или может '((... , тогда  правая и левая запятые накладываются

2018-01-22 16:21 UTC, Takhir30 commented on calc_1.py
> +            right_index = i_index
из-за случаев '((1+2)....). index вернет первое значение, а я хотел получить самую внутреннюю скобку

2018-01-22 16:21 UTC, Takhir30 commented on calc_1.py
> +    expr[left_index:right_index + 1] = [calc(expr[left_index + 1:right_index])]
done

2018-01-22 16:29 UTC, Takhir30 commented on calc_1.py
>  def trigonometry(expr):
предыдущий вариант после сортировки обрабатывал просто выражение 'sin..'
с этим это дело обстоит посложнее

2018-01-22 16:30 UTC, Takhir30 commented on calc_1.py
> +        return  float('%.2f' % float(expr[0]))
done

2018-01-22 16:37 UTC, Takhir30 commented on calc_1.py
> +    expr_list = [x for x in expr_list if x]
done

2018-01-23 08:43 UTC, strelass commented on calc_1.py
> +            right_index = i_index
но правую же можно так получить

2018-01-23 08:53 UTC, Takhir30 commented on calc_1.py
> +    expr = expr.replace(' ', '')    #Removing some extra space's
done

2018-01-23 08:58 UTC, Takhir30 commented on calc_1.py
> +            right_index = i_index
правая помогает выскочить из loop. Логика: ищем левую, пока следующая не будет правой. Как только нашли правую, выходим из loop. Полученные скобки будут парными.
А твой вариант можно тоже обыграть: найти через index правую скобку, а потом итерировать список влево до ближайшей левой скобки.

2018-01-23 10:47 UTC, strelass requested changes

2018-01-23 10:47 UTC, strelass commented on calc_1.py
> +        return calc([str(math.sin(rad_to_degree))])
опять каст к стрингу, зачем ты это делаешь?

2018-01-23 10:47 UTC, strelass commented on calc_1.py
> +    expr = expr.replace(' ', '')    #Removing some extra space's
не вижу изменений

2018-01-23 14:07 UTC, strelass approved these changes

2018-01-23 14:07 UTC, merged